apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prom-deploy
  name: prom-deploy
  namespace: prom-ns
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer
status:
  loadBalancer: {}
